// Centralized error code constants
export const ERROR_CODES = {
  // Auth & CSRF
  CSRF_INVALID: 'CSRF_INVALID',
  SIGNIN_FAILED: 'SIGNIN_FAILED',
  SIGNUP_FAILED: 'SIGNUP_FAILED',
  REFRESH_FAILED: 'REFRESH_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // Boards
  BOARDS_FETCH_FAILED: 'BOARDS_FETCH_FAILED',
  BOARDS_DELETE_FAILED: 'BOARDS_DELETE_FAILED',
  BOARDS_CREATE_FAILED: 'BOARDS_CREATE_FAILED',
  BOARDS_UPDATE_FAILED: 'BOARDS_UPDATE_FAILED',
  BOARDS_PATCH_FAILED: 'BOARDS_PATCH_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
